# Generated by Django 4.2.7 on 2025-08-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='systemhealth',
            unique_together={('component', 'checked_at')},
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='api_apiacce_user_id_faa6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['endpoint', 'timestamp'], name='api_apiacce_endpoin_3347eb_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['status_code', 'timestamp'], name='api_apiacce_status__0ab135_idx'),
        ),
    ]
