# Generated by Django 4.2.7 on 2025-08-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavioranalysis',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviors', to='detection.platform'),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['metric_type', 'start_date', 'end_date'], name='analytics_t_metric__189521_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetrics',
            unique_together={('category', 'metric_name', 'recorded_at')},
        ),
        migrations.AlterUniqueTogether(
            name='geographicanalysis',
            unique_together={('country', 'region', 'city', 'analysis_date')},
        ),
    ]
