# Generated by Django 4.2.7 on 2025-08-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='alertmetrics',
            unique_together={('alert_type', 'analysis_date')},
        ),
        migrations.AddIndex(
            model_name='userbehavioranalysis',
            index=models.Index(fields=['user_id', 'platform', 'behavior_type'], name='analytics_u_user_id_5f9d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalysis',
            index=models.Index(fields=['risk_score', 'created_at'], name='analytics_u_risk_sc_648a9e_idx'),
        ),
    ]
