# Generated by Django 4.2.7 on 2025-08-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='detection_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detection.detectionpattern'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.platform'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionpattern',
            name='drug_categories',
            field=models.ManyToManyField(blank=True, to='detection.drugcategory'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['status', 'severity_level'], name='detection_d_status_ad3058_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['platform', 'detected_at'], name='detection_d_platfor_3c82f1_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['assigned_to', 'status'], name='detection_d_assigne_b7b628_idx'),
        ),
    ]
