# Generated by Django 4.2.7 on 2025-08-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectedcontent',
            name='monitoring_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_content', to='monitoring.monitoringsession'),
        ),
        migrations.AddIndex(
            model_name='collectedcontent',
            index=models.Index(fields=['content_type', 'collected_at'], name='monitoring__content_fc9fde_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedcontent',
            index=models.Index(fields=['is_suspicious', 'collected_at'], name='monitoring__is_susp_9dcea5_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedcontent',
            index=models.Index(fields=['monitoring_session', 'collected_at'], name='monitoring__monitor_80282a_idx'),
        ),
    ]
